#include <fstream>
#include <string>
#include <vector>
#include <cmath>

#include <stdint.h>

using namespace std;

typedef unsigned int uint128_t __attribute__((mode(TI)));

/*
* Zero all values in the vector from the given index to the end.
* 
* :param vec: The vector to zero.
* : param start_idx: The index to start zeroing from.
*/
void zero_from(vector<uint8_t>& vec, size_t start_idx)
{
    for (size_t idx = start_idx; idx < vec.size(); idx++)
    {
        vec[idx] = 0;
    }
}

/*
Compute the maximal joltage for a given battery bank if 2 batteries can be turned on.

:param bank: The bank as a vector of uint8_t.

:returns: The maximum joltage generated by the bank.
*/
uint8_t max_joltage_2(vector<uint8_t>& bank)
{
    uint8_t first_battery = 0;
    uint8_t second_battery = 0;

    for (auto battery_iterator = bank.begin(); battery_iterator != bank.end(); battery_iterator++)
    {
        if (*battery_iterator > first_battery && next(battery_iterator) != bank.end())
        {
            // Found a new maximum.
            first_battery = *battery_iterator;
            // New search for second battery.
            second_battery = 0;
        }
        else if (*battery_iterator > second_battery)
        {
            // Found new better pairing.
            second_battery = *battery_iterator;
        }
    }

    return 10 * first_battery + second_battery;
}

/*
Compute the maximal joltage for a given battery bank if 12 batteries can be turned on.

:param bank: The bank as a vector of uint8_t.
:param best_batteries: The vector to be filled with the best batteries.
*/
void max_joltage_12(vector<uint8_t>& bank, vector<uint8_t>& best_batteries)
{

    for (size_t bank_idx = 0; bank_idx < bank.size(); bank_idx++)
    {
        size_t batteries_to_check = bank.size() - bank_idx;
        batteries_to_check = (batteries_to_check <= 12 ? batteries_to_check : 12);
        uint8_t battery_start_index = 12 - batteries_to_check;  // Will be in range 0-11.

        for (uint8_t battery_idx = battery_start_index; battery_idx < 12; battery_idx++)
        {
            if (bank[bank_idx] > best_batteries[battery_idx])
            {
                // Found a better battery.
                best_batteries[battery_idx] = bank[bank_idx];
                // Reset later batteries.
                zero_from(best_batteries, battery_idx + 1);

                break;
            }
        }
    }

}

int main()
{
    // Read single line input.
    ifstream file("input.txt");
    string line;

    uint64_t joltage_sum_2 = 0;
    vector<vector<uint8_t>> best_for_12 = {};

    while(getline(file, line))
    {
        vector<uint8_t> battery;

        for (string::iterator it = line.begin(); it != line.end(); it++)
        {
            battery.push_back(static_cast<uint8_t>(*it - '0'));
        }

        // Part 1
        uint8_t joltage_2 = max_joltage_2(battery);
        joltage_sum_2 += joltage_2;

        // Part 2
        vector<uint8_t> best_batteries = {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
        max_joltage_12(battery, best_batteries);
        best_for_12.push_back(best_batteries);
        
        printf("For battery %s we found joltage of %u.\n", line.c_str(), joltage_2);
    }

    printf("[Part 1] Parsed all battery banks. Total joltage: %u.\n", joltage_sum_2);

    // Evaluate Part 2 results - just because the joltage are way over uint64_t.
    vector<uint8_t> result_digits = {};

    uint64_t carry = 0;
    int8_t digit_idx = 0;
    
    while (carry != 0 || digit_idx < 12) {
        // Calculate sum for this digit.
        uint64_t digit_sum = carry;

        if (digit_idx < 12)
        {
            // Add the digits from all best results.
            for (size_t bank_idx = 0; bank_idx < best_for_12.size(); bank_idx++)
            {
                digit_sum += best_for_12[bank_idx][11 - digit_idx];
            }
        }

        // Append the result and calcualte the carry.
        result_digits.push_back(digit_sum % 10);
        carry = digit_sum / 10;
        digit_idx++;
    }

    // Print the digits in reverse to get the right order.
    printf("[Part 2] Full joltage is (digits %u):  ", result_digits.size());
    for (vector<uint8_t>::reverse_iterator ri = result_digits.rbegin(); ri != result_digits.rend(); ri++)
    {
        printf("%u", *ri);
    }
    printf(".\n");

    return 0;

}