#include <fstream>
#include <string>
#include <vector>
#include <cmath>

#include <stdint.h>

using namespace std;

/*
* Zero all values in the vector from the given index to the end.
* 
* :param vec: The vector to zero.
* : param start_idx: The index to start zeroing from.
*/
void zero_from(vector<uint8_t>& vec, size_t start_idx)
{
    for (size_t idx = start_idx; idx < vec.size(); idx++)
    {
        vec[idx] = 0;
    }
}

/*
Compute the maximal joltage for a given battery bank if 2 batteries can be turned on.

:param bank: The bank as a vector of uint8_t.

:returns: The maximum joltage generated by the bank for 2 batteries.
*/
uint8_t max_joltage_2(vector<uint8_t>& bank)
{
    uint8_t first_battery = 0;
    uint8_t second_battery = 0;

    for (auto battery_iterator = bank.begin(); battery_iterator != bank.end(); battery_iterator++)
    {
        if (*battery_iterator > first_battery && next(battery_iterator) != bank.end())
        {
            // Found a new maximum.
            first_battery = *battery_iterator;
            // New search for second battery.
            second_battery = 0;
        }
        else if (*battery_iterator > second_battery)
        {
            // Found new better pairing.
            second_battery = *battery_iterator;
        }
    }

    return 10 * first_battery + second_battery;
}

/*
Compute the maximal joltage for a given battery bank if 12 batteries can be turned on.

:param bank: The bank as a vector of uint8_t.

:returns: The maximum joltage generated by the bank for 12 batteries.
*/
uint64_t max_joltage_12(vector<uint8_t>& bank)
{
    vector<uint8_t> best_batteries = {0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u};
    for (size_t bank_idx = 0; bank_idx < bank.size(); bank_idx++)
    {
        size_t batteries_to_check = bank.size() - bank_idx;
        batteries_to_check = (batteries_to_check <= 12 ? batteries_to_check : 12);
        uint8_t battery_start_index = 12 - batteries_to_check;  // Will be in range 0-11.

        for (uint8_t battery_idx = battery_start_index; battery_idx < 12; battery_idx++)
        {
            if (bank[bank_idx] > best_batteries[battery_idx])
            {
                // Found a better battery.
                best_batteries[battery_idx] = bank[bank_idx];
                // Reset later batteries.
                zero_from(best_batteries, battery_idx + 1);

                break;
            }
        }
    }

    uint64_t resulting_joltage = 0;
    for(size_t bidx = 0; bidx < best_batteries.size(); bidx++)
    {
        resulting_joltage += best_batteries[bidx] * pow(10, 11 - bidx);
    }

    return resulting_joltage;

}

int main()
{
    ifstream file("input.txt");
    string line;

    uint64_t joltage_sum_2 = 0;
    uint64_t joltage_sum_12 = 0;

    while(getline(file, line))
    {
        vector<uint8_t> battery;

        for (string::iterator it = line.begin(); it != line.end(); it++)
        {
            battery.push_back(static_cast<uint8_t>(*it - '0'));
        }

        uint8_t joltage_2 = max_joltage_2(battery);
        joltage_sum_2 += joltage_2;
        uint64_t joltage_12 = max_joltage_12(battery);
        joltage_sum_12 += joltage_12;
        
        printf("For battery %s we found joltage of %u.\n", line.c_str(), joltage_2);
    }

    printf("[Part 1] Parsed all battery banks. Total joltage: %u.\n", joltage_sum_2);
    printf("[Part 2] Full joltage is: %llu\n", joltage_sum_12);

    return 0;

}